apiVersion: v1
kind: Service
metadata:
  name: echo-web-server
  labels:
    app: echo-web-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30002
  selector:
    app: echo-web-server