apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-web-server
  labels:
    app: echo-web-server
spec:
  selector:
    matchLabels:
      app: echo-web-server
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-web-server
    spec:
      containers:
        - name: echo-web-server
          image: registry.cn-hangzhou.aliyuncs.com/acs/echo-web-server:v1.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
            - containerPort: 8080